/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-tenna
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_TENNA_API_H
#define INCLUDED_TENNA_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_tenna_EXPORTS
#define TENNA_API __GR_ATTR_EXPORT
#else
#define TENNA_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_TENNA_API_H */
