# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gotenna_packet/proto/base_message.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gotenna_packet.proto import header_pb2 as gotenna__packet_dot_proto_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'gotenna_packet/proto/base_message.proto\x1a!gotenna_packet/proto/header.proto\"C\n\rPBBaseMessage\x12\x1d\n\x06header\x18\x01 \x01(\x0b\x32\r.PBBaseHeader\x12\x13\n\x0bmessageData\x18\x02 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gotenna_packet.proto.base_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PBBASEMESSAGE']._serialized_start=78
  _globals['_PBBASEMESSAGE']._serialized_end=145
# @@protoc_insertion_point(module_scope)
