# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gotenna_packet/proto/data_type.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$gotenna_packet/proto/data_type.proto*\xff\x01\n\x11PBMessageDataType\x12\x12\n\x0eGROUP_CREATION\x10\x00\x12\x0e\n\nMAP_OBJECT\x10\x01\x12\x0b\n\x07REQUEST\x10\x02\x12\x08\n\x04TEXT\x10\x03\x12\r\n\tFREQUENCY\x10\x04\x12\x08\n\x04PING\x10\x05\x12\x14\n\x10\x45MERGENCY_BEACON\x10\x06\x12\x16\n\x12PUBLIC_KEY_REQUEST\x10\x07\x12\x17\n\x13PUBLIC_KEY_RESPONSE\x10\x08\x12\x10\n\x0c\x42ROADCAST_QR\x10\t\x12\x07\n\x03PLI\x10\n\x12\x13\n\x0fSHARED_LOCATION\x10\x0b\x12\x0f\n\x0b\x43OMMS_CHECK\x10\x0c\x12\x0e\n\nMANUAL_PLI\x10\r*e\n\x0ePBGeofenceType\x12\x13\n\x0fGEOFENCING_NONE\x10\x00\x12\x14\n\x10GEOFENCING_ENTRY\x10\x01\x12\x13\n\x0fGEOFENCING_EXIT\x10\x02\x12\x13\n\x0fGEOFENCING_BOTH\x10\x03*V\n\x0bPBPowerType\x12\r\n\tHALF_WATT\x10\x00\x12\x0c\n\x08ONE_WATT\x10\x01\x12\x0c\n\x08TWO_WATT\x10\x02\x12\r\n\tFOUR_WATT\x10\x03\x12\r\n\tFIVE_WATT\x10\x04*B\n\x0fPBBandwidthType\x12\x0e\n\nBW_4_84KHZ\x10\x00\x12\x0e\n\nBW_7_28KHZ\x10\x01\x12\x0f\n\x0b\x42W_11_80KHZ\x10\x02*4\n\tPBPinType\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\r\n\tEMERGENCY\x10\x01\x12\x0b\n\x07WARNING\x10\x02*.\n\x12PBConversationType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x43OMMAND\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gotenna_packet.proto.data_type_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PBMESSAGEDATATYPE']._serialized_start=41
  _globals['_PBMESSAGEDATATYPE']._serialized_end=296
  _globals['_PBGEOFENCETYPE']._serialized_start=298
  _globals['_PBGEOFENCETYPE']._serialized_end=399
  _globals['_PBPOWERTYPE']._serialized_start=401
  _globals['_PBPOWERTYPE']._serialized_end=487
  _globals['_PBBANDWIDTHTYPE']._serialized_start=489
  _globals['_PBBANDWIDTHTYPE']._serialized_end=555
  _globals['_PBPINTYPE']._serialized_start=557
  _globals['_PBPINTYPE']._serialized_end=609
  _globals['_PBCONVERSATIONTYPE']._serialized_start=611
  _globals['_PBCONVERSATIONTYPE']._serialized_end=657
# @@protoc_insertion_point(module_scope)
