# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gotenna_packet/proto/frequency.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gotenna_packet.proto import data_type_pb2 as gotenna__packet_dot_proto_dot_data__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$gotenna_packet/proto/frequency.proto\x1a$gotenna_packet/proto/data_type.proto\".\n\tPBChannel\x12\r\n\x05hertz\x18\x01 \x01(\r\x12\x12\n\nis_control\x18\x02 \x01(\x08\"\xad\x01\n\x0bPBFrequency\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcall_sign\x18\x03 \x01(\t\x12\x1b\n\x05power\x18\x04 \x01(\x0e\x32\x0c.PBPowerType\x12#\n\tbandwidth\x18\x05 \x01(\x0e\x32\x10.PBBandwidthType\x12\x10\n\x08use_only\x18\x06 \x01(\x08\x12\x1c\n\x08\x63hannels\x18\x07 \x03(\x0b\x32\n.PBChannelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gotenna_packet.proto.frequency_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PBCHANNEL']._serialized_start=78
  _globals['_PBCHANNEL']._serialized_end=124
  _globals['_PBFREQUENCY']._serialized_start=127
  _globals['_PBFREQUENCY']._serialized_end=300
# @@protoc_insertion_point(module_scope)
