# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gotenna_packet/proto/location.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gotenna_packet.proto import data_type_pb2 as gotenna__packet_dot_proto_dot_data__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#gotenna_packet/proto/location.proto\x1a$gotenna_packet/proto/data_type.proto\"\x90\x02\n\x0bPBShapeData\x12\r\n\x05\x63olor\x18\x01 \x01(\r\x12&\n\rgeofence_type\x18\x02 \x01(\x0e\x32\x0f.PBGeofenceType\x12)\n\nroute_data\x18\x04 \x01(\x0b\x32\x13.PBRouteMessageDataH\x00\x12\x31\n\x0eperimeter_data\x18\x05 \x01(\x0b\x32\x17.PBPerimeterMessageDataH\x00\x12+\n\x0b\x63ircle_data\x18\x06 \x01(\x0b\x32\x14.PBCircleMessageDataH\x00\x12\x31\n\x0erectangle_data\x18\x07 \x01(\x0b\x32\x17.PBRectangleMessageDataH\x00\x42\x0c\n\nmap_object\"=\n\tPBPinData\x12\x12\n\ncoordinate\x18\x01 \x01(\x0c\x12\x1c\n\x08pin_type\x18\x02 \x01(\x0e\x32\n.PBPinType\")\n\x12PBRouteMessageData\x12\x13\n\x0b\x64\x61ta_points\x18\x01 \x01(\x0c\"-\n\x16PBPerimeterMessageData\x12\x13\n\x0b\x64\x61ta_points\x18\x01 \x01(\x0c\"5\n\x13PBCircleMessageData\x12\x0e\n\x06\x63\x65nter\x18\x01 \x01(\x0c\x12\x0e\n\x06radius\x18\x02 \x01(\x04\"M\n\x16PBRectangleMessageData\x12\x11\n\tcornerOne\x18\x01 \x01(\x0c\x12\x11\n\tcornerTwo\x18\x02 \x01(\x0c\x12\r\n\x05\x64\x65pth\x18\x03 \x01(\x0c\"3\n\x0cPBCoordinate\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gotenna_packet.proto.location_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PBSHAPEDATA']._serialized_start=78
  _globals['_PBSHAPEDATA']._serialized_end=350
  _globals['_PBPINDATA']._serialized_start=352
  _globals['_PBPINDATA']._serialized_end=413
  _globals['_PBROUTEMESSAGEDATA']._serialized_start=415
  _globals['_PBROUTEMESSAGEDATA']._serialized_end=456
  _globals['_PBPERIMETERMESSAGEDATA']._serialized_start=458
  _globals['_PBPERIMETERMESSAGEDATA']._serialized_end=503
  _globals['_PBCIRCLEMESSAGEDATA']._serialized_start=505
  _globals['_PBCIRCLEMESSAGEDATA']._serialized_end=558
  _globals['_PBRECTANGLEMESSAGEDATA']._serialized_start=560
  _globals['_PBRECTANGLEMESSAGEDATA']._serialized_end=637
  _globals['_PBCOORDINATE']._serialized_start=639
  _globals['_PBCOORDINATE']._serialized_end=690
# @@protoc_insertion_point(module_scope)
