# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gotenna_packet/proto/message.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gotenna_packet.proto import location_pb2 as gotenna__packet_dot_proto_dot_location__pb2
from gotenna_packet.proto import frequency_pb2 as gotenna__packet_dot_proto_dot_frequency__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"gotenna_packet/proto/message.proto\x1a#gotenna_packet/proto/location.proto\x1a$gotenna_packet/proto/frequency.proto\"\x90\x01\n\x16PBMapObjectMessageData\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0c\n\x04uuid\x18\x02 \x01(\x04\x12\r\n\x05title\x18\x03 \x01(\t\x12\x1d\n\x05shape\x18\x04 \x01(\x0b\x32\x0c.PBShapeDataH\x00\x12\x19\n\x03pin\x18\x05 \x01(\x0b\x32\n.PBPinDataH\x00\x42\x0c\n\nmap_object\"\x90\x01\n\x15PBLocationMessageData\x12\x12\n\ncoordinate\x18\x01 \x01(\x0c\x12#\n\x1bpli_sharing_frequency_index\x18\x02 \x01(\r\x12\x1d\n\x15pli_location_accuracy\x18\x03 \x01(\r\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x12\x0c\n\x04text\x18\x05 \x01(\t\"$\n\x14PBRequestMessageData\x12\x0c\n\x04text\x18\x01 \x01(\t\"/\n\x11PBTextMessageData\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"G\n\x16PBFrequencyMessageData\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1f\n\tfrequency\x18\x02 \x01(\x0b\x32\x0c.PBFrequency\"\xa9\x01\n\x1aPBGroupCreationMessageData\x12@\n\rgroup_members\x18\x01 \x03(\x0b\x32).PBGroupCreationMessageData.PBGroupMember\x12\x18\n\x10group_shared_key\x18\x02 \x01(\x0c\x12\x11\n\tgroup_gid\x18\x03 \x01(\x04\x1a\x1c\n\rPBGroupMember\x12\x0b\n\x03gid\x18\x01 \x01(\x04\",\n\x16PBPublicKeyMessageData\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\"a\n\x18PBBroadcastQrMessageData\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\x0c\n\x04uuid\x18\x02 \x01(\x0c\x12\x0c\n\x04salt\x18\x03 \x01(\x0c\x12\n\n\x02iv\x18\x04 \x01(\x0c\x12\x0f\n\x07keyData\x18\x05 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gotenna_packet.proto.message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PBMAPOBJECTMESSAGEDATA']._serialized_start=114
  _globals['_PBMAPOBJECTMESSAGEDATA']._serialized_end=258
  _globals['_PBLOCATIONMESSAGEDATA']._serialized_start=261
  _globals['_PBLOCATIONMESSAGEDATA']._serialized_end=405
  _globals['_PBREQUESTMESSAGEDATA']._serialized_start=407
  _globals['_PBREQUESTMESSAGEDATA']._serialized_end=443
  _globals['_PBTEXTMESSAGEDATA']._serialized_start=445
  _globals['_PBTEXTMESSAGEDATA']._serialized_end=492
  _globals['_PBFREQUENCYMESSAGEDATA']._serialized_start=494
  _globals['_PBFREQUENCYMESSAGEDATA']._serialized_end=565
  _globals['_PBGROUPCREATIONMESSAGEDATA']._serialized_start=568
  _globals['_PBGROUPCREATIONMESSAGEDATA']._serialized_end=737
  _globals['_PBGROUPCREATIONMESSAGEDATA_PBGROUPMEMBER']._serialized_start=709
  _globals['_PBGROUPCREATIONMESSAGEDATA_PBGROUPMEMBER']._serialized_end=737
  _globals['_PBPUBLICKEYMESSAGEDATA']._serialized_start=739
  _globals['_PBPUBLICKEYMESSAGEDATA']._serialized_end=783
  _globals['_PBBROADCASTQRMESSAGEDATA']._serialized_start=785
  _globals['_PBBROADCASTQRMESSAGEDATA']._serialized_end=882
# @@protoc_insertion_point(module_scope)
